import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'PROD001',
    tenantId: 'tenant-1',
    name: 'Classic White T-Shirt',
    description: 'A classic crewneck t-shirt in white, made from 100% premium cotton.',
    sku: 'TS-CW-M',
    categoryId: 'tops',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 15,
    price: 25.0,
    imageUrl: 'https://picsum.photos/seed/PROD001/400/400',
    supplierId: 'SUP001',
    averageDailySales: 5,
    leadTimeDays: 7,
  },
  {
    id: 'PROD002',
    tenantId: 'tenant-1',
    name: 'Wireless Over-Ear Headphones',
    description: 'High-fidelity wireless over-ear headphones with noise-cancellation.',
    sku: 'HD-WOH-BLK',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 35,
    price: 149.99,
    imageUrl: 'https://picsum.photos/seed/PROD002/400/400',
    supplierId: 'SUP002',
    averageDailySales: 2,
    leadTimeDays: 14,
  },
  {
    id: 'PROD003',
    tenantId: 'tenant-1',
    name: 'Artisanal Coffee Beans',
    description: 'A 1kg bag of artisanal whole coffee beans, single-origin from Ethiopia.',
    sku: 'CB-AO-1KG',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 50,
    price: 35.5,
    imageUrl: 'https://picsum.photos/seed/PROD003/400/400',
    supplierId: 'SUP003',
    averageDailySales: 10,
    leadTimeDays: 5,
  },
  {
    id: 'PROD004',
    tenantId: 'tenant-1',
    name: 'Minimalist Leather Wallet',
    description: 'A slim, minimalist leather wallet with RFID blocking technology.',
    sku: 'WT-ML-BRN',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 5,
    price: 59.95,
    imageUrl: 'https://picsum.photos/seed/PROD004/400/400',
    supplierId: 'SUP001',
    averageDailySales: 3,
    leadTimeDays: 10,
  },
  {
    id: 'PROD005',
    tenantId: 'tenant-1',
    name: 'Fitness Tracker Smartwatch',
    description: 'A sleek smartwatch with comprehensive fitness tracking capabilities.',
    sku: 'SW-FT-GRY',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 25,
    price: 199.0,
    imageUrl: 'https://picsum.photos/seed/PROD005/400/400',
    supplierId: 'SUP002',
    averageDailySales: 4,
    leadTimeDays: 12,
  },
  {
    id: 'PROD006',
    tenantId: 'tenant-1',
    name: 'Waterproof Commuter Backpack',
    description: 'A durable, waterproof backpack designed for the daily commute.',
    sku: 'BP-WC-BLK',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 30,
    price: 89.99,
    imageUrl: 'https://picsum.photos/seed/PROD006/400/400',
    supplierId: 'SUP001',
    averageDailySales: 6,
    leadTimeDays: 8,
  },
  {
    id: 'PROD007',
    tenantId: 'tenant-1',
    name: 'Slim Fit Blue Jeans',
    description: 'A pair of classic slim-fit blue denim jeans for everyday wear.',
    sku: 'JN-SF-BLU-32',
    categoryId: 'bottoms',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 40,
    price: 75.0,
    imageUrl: 'https://picsum.photos/seed/PROD007/400/400',
    supplierId: 'SUP001',
    averageDailySales: 7,
    leadTimeDays: 9,
  },
  {
    id: 'PROD008',
    tenantId: 'tenant-1',
    name: 'Insulated Steel Water Bottle',
    description: 'A 32oz stainless steel insulated water bottle, keeps drinks cold for 24 hours.',
    sku: 'WB-IS-32-SIL',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 0,
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/PROD008/400/400',
    supplierId: 'SUP003',
    averageDailySales: 8,
    leadTimeDays: 6,
  },
  {
    id: 'PROD009',
    tenantId: 'tenant-1',
    name: 'Succulent Plant Set',
    description: 'A set of three beautiful succulent plants in ceramic pots.',
    sku: 'PL-SUC-SET3',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 20,
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/PROD009/400/400',
    supplierId: 'SUP003',
    averageDailySales: 1,
    leadTimeDays: 4,
  },
  {
    id: 'PROD010',
    tenantId: 'tenant-1',
    name: 'RGB Gaming Mouse',
    description: 'A high-performance gaming mouse with customizable RGB lighting.',
    sku: 'MO-GAM-RGB',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 18,
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/PROD010/400/400',
    supplierId: 'SUP002',
    averageDailySales: 2,
    leadTimeDays: 15,
  },
];
